name: Auto Format Markdown

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write

jobs:
  format:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: markdown linter
        uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v0.17.2
        with:
          fix: true
          config: 'config/.markdownlint.json'
          globs: |
            README.md

      - name: commit markdownlint fixes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v5
        with:
          commit_message: "chore: apply markdownlint fixes [skip ci]"
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          file_pattern: README.md
