name: Manually Executed Workflow

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Doc: https://github.com/marketplace/actions/markdownlint-cli2-action
      - name: markdown linter
        uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v0.17.2
        with:
          fix: true
          config: 'config/.markdownlint.json'
          globs: |
            README.md

      - name: install pdf toolchain
        run: bash scripts/install-pdf-deps.sh

      - name: convert markdown to pdf
        run: pandoc README.md --defaults=config/pandoc/pdf.yml

      - name: upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: my-resume
          path: resume.pdf
